FROM node:20-alpine

RUN apk add --no-cache libc6-compat
WORKDIR /app

ARG NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY
ARG CLERK_SECRET_KEY
ARG NEXT_PUBLIC_CLERK_SIGN_IN_URL
ARG NEXT_PUBLIC_CLERK_SIGN_UP_URL
ARG NEXT_PUBLIC_CLERK_AFTER_SIGN_IN_URL
ARG NEXT_PUBLIC_CLERK_AFTER_SIGN_UP_URL
ARG CONVEX_DEPLOYMENT
ARG NEXT_PUBLIC_CONVEX_URL
ARG NEXT_PUBLIC_BASE_URL
ARG NEXT_PUBLIC_CONVEX_DEPLOYMENT_TOKEN
ARG NEXT_PUBLIC_DEEPGRAM_API_KEY
ARG NEXT_PUBLIC_OPEN_ROUTER_API_KEY
ARG NEXT_PUBLIC_AWS_ACCESS_KEY
ARG NEXT_PUBLIC_AWS_SECRET_ACCESS_TOKEN
ARG NEXT_PUBLIC_ARGJECT_KEY

ENV NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=$NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY \
    CLERK_SECRET_KEY=$CLERK_SECRET_KEY \
    NEXT_PUBLIC_CLERK_SIGN_IN_URL=$NEXT_PUBLIC_CLERK_SIGN_IN_URL \
    NEXT_PUBLIC_CLERK_SIGN_UP_URL=$NEXT_PUBLIC_CLERK_SIGN_UP_URL \
    NEXT_PUBLIC_CLERK_AFTER_SIGN_IN_URL=$NEXT_PUBLIC_CLERK_AFTER_SIGN_IN_URL \
    NEXT_PUBLIC_CLERK_AFTER_SIGN_UP_URL=$NEXT_PUBLIC_CLERK_AFTER_SIGN_UP_URL \
    CONVEX_DEPLOYMENT=$CONVEX_DEPLOYMENT \
    NEXT_PUBLIC_CONVEX_URL=$NEXT_PUBLIC_CONVEX_URL \
    NEXT_PUBLIC_BASE_URL=$NEXT_PUBLIC_BASE_URL \
    NEXT_PUBLIC_CONVEX_DEPLOYMENT_TOKEN=$NEXT_PUBLIC_CONVEX_DEPLOYMENT_TOKEN \
    NEXT_PUBLIC_DEEPGRAM_API_KEY=$NEXT_PUBLIC_DEEPGRAM_API_KEY \
    NEXT_PUBLIC_OPEN_ROUTER_API_KEY=$NEXT_PUBLIC_OPEN_ROUTER_API_KEY \
    NEXT_PUBLIC_AWS_ACCESS_KEY=$NEXT_PUBLIC_AWS_ACCESS_KEY \
    NEXT_PUBLIC_AWS_SECRET_ACCESS_TOKEN=$NEXT_PUBLIC_AWS_SECRET_ACCESS_TOKEN \
    NEXT_PUBLIC_ARGJECT_KEY=$NEXT_PUBLIC_ARGJECT_KEY \

    NODE_ENV=production

COPY package.json package-lock.json* ./
# RUN npm install --loglevel info
RUN npm ci --include=dev

COPY . .


RUN npm run build

EXPOSE 3000

CMD ["npm", "start"]
