name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: 91.107.243.209
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            source ~/.bashrc
            source ~/.profile
            export PATH=$PATH:/usr/local/bin:/home/ubuntu/.nvm/versions/node/*/bin

            cd /var/www/voicecoachai
            git reset --hard
            git clean -fd
            git pull origin main

            npm install
            npm run build

            pm2 restart voicecoachai
